export const TodoList =  { 
								todoItem0: { description: 'Clean fireplace & chimney' ,
									status: 'active',
									frequency: '12',
								 },
								todoItem1: {   description: 'Clean around dryer & vents' ,
									status: 'active',
									frequency: '12',
									},
								todoItem2: {
									description: 'Deep clean carpet & upholstery',
									status: 'active',
									frequency: '12',
								},
								todoItem3: {
									description: 'Clean drapes & curtains' ,
									status: 'active',
									frequency: '12',
								},
								todoItem4: {
									description: 'Deep clean windows' ,
									status: 'active',
									frequency: '12',
								},
								todoItem5: {
									description: 'Clear out gutter' ,
									status: 'active',
									frequency: '12',
								},
								todoItem6: {
									description: 'Clean inside of refrigerator' ,
									status: 'active',
									frequency: '3',
								},
								todoItem7: { 
									description: 'Wash pillows and comforters' ,
									status: 'active',
									frequency: '3',
								},
								todoItem8: { description: 'Vacuum Mattress' ,
									status: 'active',
									frequency: '6',
								},
								todoItem9: { description: 'Wash shower curtain & liner' ,
									status: 'active',
									frequency: '6',
								},
								todoItem10: { description: 'De-scale coffeemaker & tea kettle' ,
									status: 'active',
									frequency: '6',
								},
								todoItem11: { description: 'Clean inside of oven' ,
									status: 'active',
									frequency: '3',
								},
								todoItem12: { description: 'Freshen drains' ,
									status: 'active',
									frequency: '3',
								},
								todoItem13: { description: 'Clean inside of oven' ,
									status: 'active',
									frequency: '3',
								},
								todoItem14: { description: 'Clean under & behind all furniture' ,
									status: 'active',
									frequency: '3',
								},
								todoItem15: { description: 'Clean patio surfaces & deck furniture' ,
									status: 'active',
									frequency: '6',
								},
								todoItem16: { description: 'Clean out freezer' ,
									status: 'active',
									frequency: '3',
								},
								todoItem17: { description: 'Vacuum vents & woodwork' ,
									status: 'active',
									frequency: '6',
								},
								todoItem18: { description: 'Dust & clean light fixtures' ,
									status: 'active',
									frequency: '3',
								},
								todoItem19: { description: 'Dust blinds' ,
									status: 'active',
									frequency: '6',
								},
								todoItem20: { description: 'Clean your dishwasher and vacuum' ,
									status: 'active',
									frequency: '3',
								},
								todoItem21: { description: 'Scrub the grout' ,
									status: 'active',
									frequency: '3',
								},
								todoItem22: { description: 'Sort through closets' ,
									status: 'active',
									frequency: '6',
								},
								todoItem23: { description: 'Flip mattress' ,
									status: 'active',
									frequency: '6',
								},
								todoItem24: { description: 'Wash walls, trim and door' ,
									status: 'active',
									frequency: '6',
								},
								todoItem25: { description: 'Dust shelves' ,
									status: 'active',
									frequency: '3',
								},
								todoItem26: { description: 'Clean small electronics' ,
									status: 'active',
									frequency: '6',
								},
								todoItem27: { description: 'Clean out pantry' ,
									status: 'active',
									frequency: '6',
								},
								todoItem28: { description: 'Wash outerwear' ,
									status: 'active',
									frequency: '12',
								},
								todoItem29: { description: 'Clean light switches' ,
									status: 'active',
									frequency: '12',
								},
								todoItem30: { description: 'Dust decorative accents' ,
									status: 'active',
									frequency: '6',
								},
							}
						


